openapi: 3.0.3
info:
  title: Your Project API
  version: 1.0.0
  description: Your project description
paths:
  /account/email-verify:
    get:
      operationId: account_email_verify_retrieve
      parameters:
      - in: query
        name: token
        schema:
          type: string
        description: access_token
      tags:
      - account
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /account/login:
    post:
      operationId: account_login_create
      tags:
      - account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Login'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Login'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Login'
          description: ''
  /account/logout:
    post:
      operationId: account_logout_create
      tags:
      - account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Logout'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Logout'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Logout'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Logout'
          description: ''
  /account/mobile-verify:
    post:
      operationId: account_mobile_verify_create
      tags:
      - account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfirmOTP'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ConfirmOTP'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ConfirmOTP'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfirmOTP'
          description: ''
  /account/new-password:
    patch:
      operationId: account_new_password_partial_update
      tags:
      - account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedSetNewPassword'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedSetNewPassword'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedSetNewPassword'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SetNewPassword'
          description: ''
  /account/password-reset-complete:
    patch:
      operationId: account_password_reset_complete_partial_update
      description: set new password for requested password reset email
      tags:
      - account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedForgetPassword'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedForgetPassword'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedForgetPassword'
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForgetPassword'
          description: ''
  /account/password-reset/{uidb64}/{token}:
    get:
      operationId: account_password_reset_retrieve
      parameters:
      - in: path
        name: token
        schema:
          type: string
        required: true
      - in: path
        name: uidb64
        schema:
          type: string
        required: true
      tags:
      - account
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForgetPassword'
          description: ''
  /account/register:
    post:
      operationId: account_register_create
      tags:
      - account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Register'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Register'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Register'
          description: ''
  /account/request-otp:
    get:
      operationId: account_request_otp_retrieve
      parameters:
      - in: query
        name: mobile_number
        schema:
          type: string
        description: mobile_number
        required: true
      tags:
      - account
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /account/request-reset-password:
    post:
      operationId: account_request_reset_password_create
      tags:
      - account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordEmailRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ResetPasswordEmailRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ResetPasswordEmailRequest'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResetPasswordEmailRequest'
          description: ''
  /account/token/refresh:
    post:
      operationId: account_token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /api/schema/:
    get:
      operationId: api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - api
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  schemas:
    ConfirmOTP:
      type: object
      properties:
        otp:
          type: string
          maxLength: 6
          minLength: 4
        mobile_number:
          type: string
          maxLength: 14
          minLength: 11
      required:
      - mobile_number
      - otp
    ForgetPassword:
      type: object
      properties:
        password:
          type: string
          writeOnly: true
          maxLength: 68
          minLength: 6
        token:
          type: string
          writeOnly: true
          minLength: 1
        uidb64:
          type: string
          writeOnly: true
          minLength: 1
      required:
      - password
      - token
      - uidb64
    Login:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          writeOnly: true
          maxLength: 68
          minLength: 6
        tokens:
          type: string
          readOnly: true
        mobile_number:
          type: string
      required:
      - password
      - tokens
    Logout:
      type: object
      properties:
        refresh:
          type: string
      required:
      - refresh
    PatchedForgetPassword:
      type: object
      properties:
        password:
          type: string
          writeOnly: true
          maxLength: 68
          minLength: 6
        token:
          type: string
          writeOnly: true
          minLength: 1
        uidb64:
          type: string
          writeOnly: true
          minLength: 1
    PatchedSetNewPassword:
      type: object
      properties:
        password:
          type: string
          writeOnly: true
          maxLength: 68
          minLength: 6
        refresh:
          type: string
    Register:
      type: object
      properties:
        email:
          type: string
          format: email
          maxLength: 255
        mobile_number:
          type: string
          maxLength: 16
        password:
          type: string
          writeOnly: true
          maxLength: 68
          minLength: 6
        first_name:
          type: string
          maxLength: 20
        last_name:
          type: string
          maxLength: 20
      required:
      - email
      - first_name
      - last_name
      - mobile_number
      - password
    ResetPasswordEmailRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          minLength: 2
        redirect_url:
          type: string
          maxLength: 500
      required:
      - email
    SetNewPassword:
      type: object
      properties:
        password:
          type: string
          writeOnly: true
          maxLength: 68
          minLength: 6
        refresh:
          type: string
      required:
      - password
      - refresh
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          writeOnly: true
      required:
      - access
      - refresh
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
